/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class BTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new B()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
