/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class A {
    public String getGreeting() {
        return "A";
    }

    public static void main(String[] args) {
        System.out.println(new A().getGreeting());
		System.out.println(new A().getGreeting());
		System.out.println(new A().getGreeting());
		System.out.println(new A().getGreeting());
		System.out.println(new A().getGreeting());
		throw new RuntimeException();
    }
}
