/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class C {
    public String getGreeting() {
        return "C " + new B().getGreeting();
    }

    public static void main(String[] args) {
        System.out.println(new C().getGreeting());
    }
}
