/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class D {
    public String getGreeting() {
        return "B " + new A().getGreeting();
    }

    public static void main(String[] args) {
        System.out.println(new D().getGreeting());
    }
}
